language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules

# prepare deployment
after_success: yarn build

# deploy to github pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: out
  on:
    branch: master
